default: production
environments:
  local: ""
  staging: ""
  production: "https://dp.dev.qone-dev.com/"
users:
  admin:
    username: "kirill_zlotnikov+admin@quantumone.ae"
    password: "Abc123!@#"
  user:
    username: "test_user@quantumone.ae"
    password: "NewPass1234!"
    new_pass: "NewPass123!"
    password_outlook: "T!650876172432up"
