name: Python AutoTest on Azure

on:
  # Called from backend/frontend
  workflow_call:
    inputs:
      requirements_path:
        required: true
        type: string
      tests_path:
        required: true
        type: string
      environment:
        required: true
        type: string

  # Manual trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'dev'
        type: choice
        options: [dev]

  # When YOU update automation
  push:
    branches: [ main, dev ]

  # Nightly regression
  schedule:
    - cron: '0 0 * * *'

jobs:
  autotest:
    name: Run Python UI Tests
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ADMIN_USERNAME: ${{ vars.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD }}
      EMPLOYEE_USERNAME: ${{ vars.EMPLOYEE_USERNAME }}
      EMPLOYEE_PASSWORD: ${{ vars.EMPLOYEE_PASSWORD }}
      EMPLOYEE_NEW_PASSWORD: ${{ vars.EMPLOYEE_NEW_PASSWORD }}
      REQUIREMENTS_PATH: dream_platform/requirements.txt
      TESTS_PATH: dream_platform/ui/tests
      FINAL_REQUIREMENTS: ${{ inputs.requirements_path != '' && inputs.requirements_path || 'dream_platform/requirements.txt' }}
      FINAL_TESTS: ${{ inputs.tests_path != '' && inputs.tests_path || 'dream_platform/ui/tests' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $FINAL_REQUIREMENTS

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        run: |
          az login --service-principal \
            -u "$AZURE_CLIENT_ID" \
            -p "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"

      - name: Run full UI autotest suite
        run: pytest $FINAL_TESTS --junitxml=pytest-report.xml --alluredir=allure-results

      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.xml

      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt update
          sudo apt install allure -y

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
